### ISSUE TITLE
compute_Uin_from_Uquest.py umschreiben für Unit test

### ISSUE THREAD

**Issue by Mosarvit** [Mosarvit/PjSemBeschlTech#13]
test_compute_Uin_from_Uquest in python ist fertig
test_compute_Uin_from_Uquest.m funktioniert bereits in Matlab.

**Comment by JayJay0815** [comment]
in python etabliert:
- läuft momentan mit Testfehler von 0.155 durch (vgl. Octave: 0.15) bei Vergleich von Uin_ideal mit dem berechneten Uin_computed
- unklar bleibt momentan: Faktor 10, den Uin zu hoch berechnet wird
- welche Interpolation ist die beste?
- Wie kam Uin_ideal zustande? Abweichung bei Octave ist auch nennenswert!
- woher kamen die Parameter in K_param2_300 ?

**Comment by JayJay0815** [comment]
Kleine Änderungen wurden vorgenommen an
- helper overlay:  if shift > 0 -> zweite Zuweisung kleiner Dreher
- test compute_Uin_from_Uquest -> Anpassung overlay-Bedingung an Problem der unterschiedlichen Zeitschrittweiten s. oben

**Comment by Mosarvit** [comment]
- Wie kam Uin_ideal zustande? Abweichung bei Octave ist auch nennenswert!
   - Uin_ideal (+ amplitude) ist erstmal der input, um Uout_300 bzw. Uout_400 zu erhalten. Aus dem Uout_300 berechnen wir das Uquest mithilfe der Funktion von Jens compute_Uquest_from_Uout. Daraus berechnen wir dann K_param2_300

**Comment by Mosarvit** [comment]
Ich schließe die issue, da dieser Teil momentan läuft, sprich den unit test besteht, auch wenn es noch nicht am System getested wurde. Sobald probleme auftreten, machen wir es wieder auf.
