### ISSUE TITLE
Laufzeitoptimierung prüfen

### ISSUE THREAD

**Issue by JayJay0815** [Mosarvit/PjSemBeschlTech#24]
Mit commit 'laufzeit-optimierung für Versuche gestartet' wurden in unserer Implementierung der Methode `getH `und den helpers `write_to_AWG `und `read_from_DSO `Optionen eingebaut, um verschiedene Zeitabfragen zu testen, um weniger Zeit als die pauschalen 5 oder 10 sec auf das Warten auf die Geräte zu verbringen. 
Die entsprechenden Abfragen lassen sich über den jeweils lokal definierten Flag `time_attempt `auswählen. An jeder Stelle, an der vorher `times.sleep(..)` stand, sind jetzt mit diesen Abfragen für das betreffende Gerät ausgestattet und ausführlich kommentiert. 
Bitte um Test und (Bug-) Bericht beim nächsten Test-Termin

**Comment by Mosarvit** [comment]
Geprüft haben wir
